CMS_HOST: studio.edx3.sapientury.com
CONTACT_EMAIL: contact@edx3.sapientury.com
ENABLE_HTTPS: true
ID: Nr7JylE73ItvlyNYOdrQEF8B
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEowIBAAKCAQEAm844+P3m3tJh1Cv2rIxH6kVbIOpTcANOdOQV8iQUeimFioLz

  TDDpUrF305kgZRJjZQe2ZseOCuqSNmE3kTcVHkKfk0EqfGHR318oQaxZyrP2FZ7N

  Sv8rxcKacT7QHgmaBAnbwnGsMmOM0TC/S6DjARKoRyqLckMXfYiZsfvCuS3y1TTt

  Z8ZlhBZZlFXTVvX9OLKSabwQleIiajg8RPfgzRnBf3ZJwa1FtZu1F5BBOAHbAS8r

  PxFC0x3Az8i1qPd7SQIDu0EwmNplohNqj3q9/GB9Lgq4mWtnmt2W8attWz2oHkiD

  ouVYPrDaNy6ynIjHUXqu8GWgTmtg279h62s48QIDAQABAoIBAAgDf04MuqLCL8SS

  wo4xTKtft/pBXStnKyJTXy7YNNqr7y2+sqJ8B0sw3DK8pvQ14fl+wB6pE8zrT9wG

  y+2u12nqF7SyasvRGPMoDP00Pv3QW+dUprbdWSgzvD94AWqzGBouMuC9WaPRl5sE

  mqk6WCSsa831wex9h4w2EgAr3KILNrMcoMlPEoYFQ7S86Eb0oA41v+nl4wqGSe4B

  vzYKZI3I0q4oa+O8Gj7CH4koSa/FDwMG7d3uMdx63qlcs2zlaRB9VRru1rpplTp2

  dIpJfdOkWaX8/ta6UZ8h0HFSxBxD2pXNtNn5o2whkIgF1mAs4+hFMtXBQvcR8TeO

  k0bCBeECgYEAu511TEhrRPBDepvxQ4zG8RXJZaY+to7aHM1eCC77qXYzJ+j7yCKl

  BQWcL7OLJGwpgICZ6i6sCRDcv94BtVAu5ucac/JkaiTmXihJO4kzgDjQO0dppKSs

  MF7BJMrjMnUQBLN+KBvT907MeNzeSj584gc9Nxbb3D085iCUBrwO1JECgYEA1JiW

  kITRAOkNIzxzbU5yUNjMKd8Hz40fT/cXY9RSatOxvUnl7uaIBO2yAVeFcKLpGhuU

  R5eCH+tLcyPnGGBaRVvQHZgBPaZ1HgrhXHvMNZ9wDZ/RSwm4Rfx/NUZnD+WlBdEs

  D1SVYECImfHplZtFpEIq5C+FUNnH+4zL227AzmECgYAfgSBaT+rbZ7EdHKSV4ETj

  5PGtxQ3Q4AoWPhIlM6aE3VlXwVLOV6r4PentRKv/0L3jWzT9UxsGZrN68I++35kQ

  owwZHkHoZQveEcvCWJayWFf3LFW8FP7pHHA4em1OYsPu1ilAGPQuGihRv10AgJ+9

  4NNRtd/zisD4L85LlzayUQKBgEtHNJk7zl4KJ7LAZwbfbi8edTymUre1es7v6YJZ

  3k0hZKBoGFj9nFBScmNzQDbgGLY76cdn6JWw1WiR3/SLuasxlYHFHztbQ8E9jQsY

  cvjR2fWZD50Idg2iGNEeesPwRvzGUlmjU7lfYH9SX6mv73r4SwO9p/E3DE8QTecH

  UpJBAoGBAK8Y5Kjd0UhUTgOtpJm1QpWzaGA4Lk7hyBk3xGbVvWj0lOYi3LmToLhw

  TuY0pZMqvzT/RVA4P5J7L96PgjmN392MU71IAYHZAaBs4IoM2YGaI26FkT60k/gp

  TsqlXiJrpTJOAfX4Vsciomnz7Ung4sFqNBxHyiQTUG1OcE+fBsIg

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: edx3.sapientury.com
MYSQL_ROOT_PASSWORD: 2JkwC5lm
OPENEDX_MYSQL_PASSWORD: R79PpUsk
OPENEDX_SECRET_KEY: IOlQzm6dMAwTwkazR5wI500S
PLATFORM_NAME: My Open edX
PLUGINS: []
